### ISSUE TITLE
active 16s balancer firmware 

### ISSUE THREAD

**Issue by iioancristian** [all-solutions/DALY-docs-and-soft#1]
I installed by mistake I think a firmware from a BMS over active balancer 16s so now it doesn't send me anything, it could be reinstalled but it asks me for a firmware installation code and I don't know which one it is for active 16s balancer... please help me thank you!!!

**Comment by all-solutions** [comment]
Hi,
that is of course annoying. Unfortunately I can't give you any firmware installation codes, I don't have any.
But you can contact Daly directly, they will certainly be able to help you.

[https://www.dalybms.com/contact-daly/](https://www.dalybms.com/contact-daly/)
